FROM node:14.9-buster-slim AS dev

ARG NODE_ENV

ENV BUILD_DEPS="build-essential" \
  APP_DEPS="curl iputils-ping" \
  NODE_ENV=$NODE_ENV \
  IMMER_CY_APP_NAME="cra"

ADD \
  https://raw.githubusercontent.com/humpangle/wait-until/v0.1.1/wait-until \
  /usr/local/bin

COPY \
  ./entrypoint.sh \
  /usr/local/bin

RUN \
  chmod 755 /usr/local/bin/wait-until && \
  chmod 755 /usr/local/bin/entrypoint.sh && \
  mkdir -p /app/_shared &&  \
  mkdir -p /app/packages/shared &&  \
  mkdir -p /app/packages/cra && \
  chown -R node:node /app && \
  apt-get update && \
  apt-get install -y --no-install-recommends ${BUILD_DEPS} &&  \
  [ "$NODE_ENV" != "production" ] &&  \
    apt-get install -y --no-install-recommends ${APP_DEPS} &&  \
  rm -rf /var/lib/apt/lists/* &&  \
  rm -rf /usr/share/doc && rm -rf /usr/share/man &&  \
  apt-get purge -y --auto-remove ${BUILD_DEPS} &&  \
  apt-get clean

USER node

WORKDIR /app

######### ROOT FILES ##########
COPY  \
  --chown=node:node \
  ./package-scripts.js \
  ./package.json \
  ./yarn.lock \
  ./.yarnrc \
  ./

########## SHARED FOLDER ##########
COPY  \
  --chown=node:node \
  ./_shared \
  ./_shared/

######## PACKAGES/SHARED ##########
COPY  \
  --chown=node:node \
  ./packages/shared \
  ./packages/shared/
######## END PACKAGES/SHARED ########

######## CRA ##########
COPY  \
  --chown=node:node \
  ./packages/cra \
  ./packages/cra/
######## END CRA ########

RUN \
  yarn install --frozen-lockfile

CMD ["/bin/bash"]

############################### build stage ###############################

FROM dev as build

# in production, the API_URL must be known before building the image
ARG API_URL

ENV NODE_ENV="production" \
  API_URL=${API_URL}

USER node

WORKDIR /app

RUN yarn start cra.b

############################### run stage ###############################

FROM nginx:1.20.0 as prod
# docker build \
  # -t immer-cy-cra-prod \
  # -f Dockerfile.cra \
  # --target prod  \
  # --build-arg API_URL=$API_URL \
  # .

# docker run \
  # -it \
  # --rm \
  # --name immer-cy-cra-prod-1 \
  # -p $DOCKER_HOST_WEB_PORT:80 \
  # immer-cy-cra-prod:latest

COPY ./packages/cra/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/packages/cra/build /usr/share/nginx/html
